name: Build with ent-cli

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Fetch repository
      
    - name: Build bundle
      id: ent-command
      uses: pietrangelo-net/ent@main
      with:
        ent-command: ent bundle pack --org=entando --stdout
    - name: Bundle name
      run: echo "Bundle Name: ${{ steps.ent-command.outputs.bundle-name }}" 
      
      
