name: Build with ent-cli

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Fetch repository
    
    - name: Build bundle
      id: ent
      uses: entando/catalyst-infra-templates/custom-github-actions/ent@test-ent
      with:
        docker-org: 'entando'
        
    - name: Create manifests
      run: ent bundle pack --org=${{ steps.ent.inputs.docker-org }} --stdout
    
